package com.chmod777.secawarequiz.ui.theme

import androidx.compose.ui.graphics.Color

val ScreenBackground = Color(0xFFFAFAFA)
val PrimaryText = Color(0xFF212121)
val BorderColor = Color(0xFFDADADA)
val InputFieldBackground = Color(0xFFFFFFFF)
val LinkColor = Color(0xFF2196F3)
val ButtonTextColor = Color(0xFFFFFFFF)
val GoogleButtonTextColor = Color(0xFF000000)
val AccentBlue = Color(0xFF1E88E5)
val HintGray = Color(0xFF9E9E9E)
val ProfileItemIconColor = Color(0xFF424242)

val HomeSubtitleText = Color(0xFF616161)
val BottomNavBorder = Color(0xFFE0E0E0)
val BottomNavActive = Color(0xFF2196F3)
val BottomNavInactive = Color(0xFF9E9E9E)

val CardAccentPhishing = Color(0xFF4FC3F7)
val CardAccentPasswords = Color(0xFFF48FB1)
val CardAccentLiteracy = Color(0xFF64B5F6)
val CardAccentDataSecurity = Color(0xFF9575CD)

val CardAccentQuiz = CardAccentLiteracy
val CardAccentFakeLogin = CardAccentDataSecurity

val FigmaLightSurface = Color(0xFFF7FAFC)

val LightBlueNavIndicator = Color(0xFF0D80F2)

val md_theme_light_primary = Color(0xFF6200EE)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBB86FC)
val md_theme_light_onPrimaryContainer = Color(0xFF000000)
val md_theme_light_secondary = Color(0xFF03DAC6)
val md_theme_light_onSecondary = Color(0xFF000000)
val md_theme_light_secondaryContainer = Color(0xFF6FF7FF)
val md_theme_light_onSecondaryContainer = Color(0xFF000000)
val md_theme_light_tertiary = Color(0xFF03A9F4)
val md_theme_light_onTertiary = Color(0xFF000000)
val md_theme_light_tertiaryContainer = Color(0xFF81D4FA)
val md_theme_light_onTertiaryContainer = Color(0xFF000000)
val md_theme_light_error = Color(0xFFB00020)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFCD8DF)
val md_theme_light_onErrorContainer = Color(0xFF141213)
val md_theme_light_background = Color(0xFFF7F2FA)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFEF7FF)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFF5EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFFD0BCFF)
val md_theme_light_surfaceTint = md_theme_light_primary
val md_theme_light_outlineVariant = Color(0xFFCAC4D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFD0BCFF)
val md_theme_dark_onPrimary = Color(0xFF381E72)
val md_theme_dark_primaryContainer = Color(0xFF4F378B)
val md_theme_dark_onPrimaryContainer = Color(0xFFEADDFF)
val md_theme_dark_secondary = Color(0xFF03DAC6)
val md_theme_dark_onSecondary = Color(0xFF003D37)
val md_theme_dark_secondaryContainer = Color(0xFF005049)
val md_theme_dark_onSecondaryContainer = Color(0xFF6FF7FF)
val md_theme_dark_tertiary = Color(0xFF82CFFF)
val md_theme_dark_onTertiary = Color(0xFF003351)
val md_theme_dark_tertiaryContainer = Color(0xFF004A73)
val md_theme_dark_onTertiaryContainer = Color(0xFFC2E8FF)
val md_theme_dark_error = Color(0xFFCF6679)
val md_theme_dark_onError = Color(0xFF141213)
val md_theme_dark_errorContainer = Color(0xFFB00020)
val md_theme_dark_onErrorContainer = Color(0xFFFCD8DF)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFE6E1E5)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE6E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E5)
val md_theme_dark_inversePrimary = Color(0xFF6200EE)
val md_theme_dark_surfaceTint = md_theme_dark_primary
val md_theme_dark_outlineVariant = Color(0xFF49454F)
val md_theme_dark_scrim = Color(0xFF000000)
